### ISSUE TITLE
masalah sesudah add domain dan sssl

### ISSUE THREAD

**Issue by agustig** [secgron/Nginx-vHost-Auto-Installer-with-SSL-by-Let-s-Encrypt#1]
saya sudah mengikuti step sebelumnya, tidak ada masalah. pada step ini sesudah di tambahkan domain dan auto ssl masalah nya nginx tidak mau start. saya kurang paham cara troubel shooting nya, saya udah obrak-abrik google juga ga ada solusi.
tolong solusinya mas teguh.
ss http://prntscr.com/i8btkl

**Comment by teguhmicro** [comment]
Itu kesalahan ketika proses issue SSL menggunakan let's encrypt. Jadi prosesnya gagal, makanya efeknya ke nginx tidak mau di start juga karena di dalam virtual host configuration membutuhkan bagian berikut ini 

` ssl_certificate /etc/letsencrypt/live/domainkita.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/domainkita.com/privkey.pem;`

Jika proses issue SSL gagal, maka domainkita.com tidak akan ada di dir /live

Sepertinya ini bug dari let's encrypt, karena ada juga server saya yang mengalami masalah seperti ini. Tapi ada juga server saya yang berjalan normal. Masih diselidiki sampai saat ini
